language: go

services:
  - docker
  - rabbitmq

# needed for the nfpm pipe
addons:
  apt:
    packages:
    - rpm

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

env:
  - GO111MODULE=on

install: true

before_install:
  - export NODE=127.0.0.1
  - docker volume create --name etcd-data
  - export DATA_DIR="etcd-data"
  - export REGISTRY=quay.io/coreos/etcd
  - docker run -d -p 127.0.0.1:2379:2379 -p 127.0.0.1:2380:2380 --volume=${DATA_DIR}:/etcd-data --name etcd ${REGISTRY}:latest /usr/local/bin/etcd --data-dir=/etcd-data --name node --initial-advertise-peer-urls http://${NODE}:2380 --listen-peer-urls http://0.0.0.0:2380 --advertise-client-urls http://${NODE}:2379 --listen-client-urls http://0.0.0.0:2379 --initial-cluster node1=http://${NODE}:2380
  - docker ps
  - sleep 30
  - netstat -tulpn
  - curl -L http://127.0.0.1:2379/v2/stats/leader -v

# Fix this by renaming the directory before testing.
# https://github.com/travis-ci/travis-ci/issues/4573
script:
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  # Fix dir names
  - cd $GOPATH/src/github.com/
  - mv silverbackhq/Sloth silverbackhq/sloth
  - cd silverbackhq/sloth
  # Config & execute ci tasks
  - make install_revive
  - make ci
  # Workaround to clear any package used for testing only
  - git status
  - git diff > diff.log
  - cat diff.log
  - git clean -fd
  - git reset --hard

matrix:
  include:
  allow_failures:
  - go: 1.9.x
  - go: 1.10.x
  - go: master

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    go: 1.12.x
    condition: $TRAVIS_OS_NAME = linux
