# Node role agent or orchestrator or worker
role: ${SLOTH_ROLES:-agent}


# Log configs
log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${SLOTH_LOG_LEVEL:-warn}
    # output can be stdout or abs path to log file /var/logs/sloth.log
    output: ${SLOTH_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${SLOTH_LOG_FORMAT:-json}


# only if roles has agent
agent:
    hostname: ${SLOTH_AGENT_HOSTNAME:-localhost}
    validation_key: ${SLOTH_AGENT_VALIDATION_KEY:-/etc/sloth/validation.pem}
    client_key: ${SLOTH_AGENT_CLIENT_KEY:-/etc/sloth/client.pem}
    checks:
        -
            type: http
            configs:
                -
                    name: url
                    value: http://localhost
                -
                    name: method
                    value: get
                -
                    name: timeout
                    value: 5s
                -
                    name: method
                    value: get
                -
                    name: headers
                    value: x-key=value_here


# only if roles has orchestrator
orchestrator:
    key: value


# only if roles has worker
worker:
    key: value
