# Node roles
roles: ${SLOTH_ROLES:-agent,orchestrator,worker}


# Log configs
log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${SLOTH_LOG_LEVEL:-warn}
    # output can be stdout or abs path to log file /var/logs/sloth.log
    output: ${SLOTH_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${SLOTH_LOG_FORMAT:-json}


# only if roles has agent
agent:
    key: value


# only if roles has orchestrator
orchestrator:
    key: value


# only if roles has worker
worker:
    key: value
