# Agent Configs
agent:
    hostname: ${SLOTH_AGENT_HOSTNAME:-localhost}
    client_key: ${SLOTH_AGENT_CLIENT_KEY:-feF-KciSUzsx3kXipfvrw0qN0ty9fTTS}
    checks:
        -
            type: http
            configs:
                -
                    name: url
                    value: http://localhost
                -
                    name: method
                    value: get
                -
                    name: timeout
                    value: 5s
                -
                    name: method
                    value: get
                -
                    name: headers
                    value: x-key=value_here

# Worker Configs
worker:
    key: value


# API Server Configs
api:
    # HTTP port
    port: ${SLOTH_API_PORT:-8080}
    # TLS configs
    tls:
        status: ${SLOTH_API_TLS_STATUS:-off}
        pemPath: ${SLOTH_API_TLS_PEMPATH:-cert/server.pem}
        keyPath: ${SLOTH_API_TLS_KEYPATH:-cert/server.key}

    # Runtime, Requests/Response and Sloth Metrics
    metrics:
        prometheus:
            # Route for the metrics endpoint
            endpoint: ${SLOTH_API_METRICS_PROM_ENDPOINT:-/metrics}


# Env mode (dev or prod)
mode: ${SLOTH_MODE:-dev}

# Log configs
log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${SLOTH_LOG_LEVEL:-warn}
    # output can be stdout or abs path to log file /var/logs/sloth.log
    output: ${SLOTH_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${SLOTH_LOG_FORMAT:-json}


# Drivers
drivers:
    rabbitmq:
        connection: ~

    etcd:
        connection: ~
