# General App Configs
app:
    # Env mode (dev or prod)
    mode: ${SLOTH_APP_MODE:-dev}

# Log Configs
log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level:  ${SLOTH_LOG_LEVEL:-warn}
    # output can be stdout or abs path to log file /var/logs/sloth.log
    output:  ${SLOTH_LOG_OUTPUT:-stdout}
    # Format can be json
    format:  ${SLOTH_LOG_FORMAT:-json}

# Message Broker Configs
broker:
    # Broker driver (rabbitmq)
    driver: ${SLOTH_BROKER_DRIVER:-rabbitmq}

    # RabbitMQ Configs
    rabbitmq:
        connection: ${SLOTH_BROKER_CONNECTION:-amqp://guest:guest@127.0.0.1:5672}
