// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/silverbackhq/sloth/internal/app/agent"
	"github.com/silverbackhq/sloth/internal/app/api"
	"github.com/silverbackhq/sloth/internal/app/cmd"
	"github.com/silverbackhq/sloth/internal/app/worker"
)

func InitializeNewAgent() *cmd.Agent {
	config := agent.NewConfig()
	cmdAgent := cmd.NewAgent(config)
	return cmdAgent
}

func InitializeNewWorker() *cmd.Worker {
	config := worker.NewConfig()
	cmdWorker := cmd.NewWorker(config)
	return cmdWorker
}

func InitializeNewAPI() *cmd.API {
	config := api.NewConfig()
	cmdAPI := cmd.NewAPI(config)
	return cmdAPI
}
